name: 'tag pipeline'
on:
  push:
    tags:
      - 'staging-*'
      - 'production-*'
env:
  tf_version: 'latest'
  tf_working_dir: '.'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  GOOGLE_APPLICATION_CREDENTIALS: '../.gcp.json'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - uses: franzdiebold/github-env-vars-action@v1.0.0
      - run: echo "::set-output name=environment::$(echo $GITHUB_REF_NAME | cut -d- -f1)"
        shell: bash
        id: get_environment
      - run: 'echo "$GOOGLE_CLOUD_KEYFILE_JSON" > .gcp.json'
        shell: bash
        env:
          GOOGLE_CLOUD_KEYFILE_JSON: ${{secrets.GOOGLE_CLOUD_KEYFILE_JSON}}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "terraform_application"
          args: '-backend-config=environments/${{ steps.get_environment.outputs.environment }}/backend.tfvars -var-file=environments/${{ steps.get_environment.outputs.environment }}/variables.tfvars'
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        env:
          TF_VAR_image_tag: ${{ env.GITHUB_REF_NAME }}
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "terraform_application"
          args: '-var-file=environments/${{ steps.get_environment.outputs.environment }}/variables.tfvars'